### ISSUE TITLE
Pequeña duda

### ISSUE THREAD

**Issue by gcipherd** [danjrosales/cv-gcipherd#2]
Profesor, no recuerdo si ud tenía que aceptar el merge o hacerlo nosotros, pero me arriesgué y lo hice yo. Estuvo bien? Para el proyecto en equipo, cómo será?

Saludos

**Comment by DannasCornell** [comment]
> Profesor, no recuerdo si ud tenía que aceptar el merge o hacerlo nosotros, pero me arriesgué y lo hice yo. Estuvo bien? Para el proyecto en equipo, cómo será?
> 
> Saludos

Estuvo bien, en el momento que se realizó **la clonación del repositorio** ya les pertenece. 


En caso de que hicieras los cambios sobre el **repositorio original** si tendría que hacerlo yo, pero me llegaría una notificación.

Buen trabajo @gcipherd
